import type { Flat } from './types';

export const flats: readonly Flat[] = [
  {
    floor: 0,
    column: 1,
    rooms: 4,
    area: 96.2,
    price: 1423000,
    status: 'sold',
    outdoor: { kind: 'garden', area: 38 },
    note: 'Cztery pokoje i dwie łazienki: salon na wschód, sypialnie na zachód. Z ogródkiem 38 m² na dziedzińcu. Strop na wysokości 3,9 m, jak w dawnej hali.',
  },
  {
    floor: 0,
    column: 2,
    rooms: 3,
    area: 55.3,
    price: 846000,
    status: 'sold',
    outdoor: { kind: 'garden', area: 24 },
    note: 'Żeliwny słup z 1908 roku stoi w salonie i dzieli go na część jadalną i dzienną. Z sypialni wychodzi się wprost do ogródka 24 m² od strony dziedzińca. Strop ma 3,9 m.',
  },
  {
    floor: 0,
    column: 3,
    rooms: 2,
    area: 37.2,
    price: 595000,
    status: 'sold',
    outdoor: { kind: 'garden', area: 18 },
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Z ogródkiem 18 m² na dziedzińcu. Strop na wysokości 3,9 m, jak w dawnej hali.',
  },
  {
    floor: 0,
    column: 4,
    rooms: 3,
    area: 52.8,
    price: 795000,
    status: 'sold',
    outdoor: { kind: 'garden', area: 25 },
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Ogródek 25 m² przy sypialni, strop 3,9 m.',
  },
  {
    floor: 0,
    column: 7,
    rooms: 3,
    area: 59.5,
    price: 923000,
    status: 'available',
    outdoor: { kind: 'garden', area: 22 },
    note: 'Słup żeliwny zostaje w salonie, wyczyszczony i zaznaczony na rzucie. Ogródek 22 m² leży przy sypialni, a strop ma 3,9 m, jak w dawnej hali.',
  },
  {
    floor: 0,
    column: 8,
    rooms: 2,
    area: 36.4,
    price: 554000,
    status: 'reserved',
    outdoor: { kind: 'garden', area: 17 },
    note: 'Salon z aneksem na wschód, cicha sypialnia na zachód. Parter z ogródkiem 17 m² od strony dziedzińca i pokojami wysokimi na 3,9 m.',
  },
  {
    floor: 0,
    column: 9,
    rooms: 3,
    area: 51.6,
    price: 801000,
    status: 'sold',
    outdoor: { kind: 'garden', area: 24 },
    note: 'Słup z 1908 roku stoi między aneksem a częścią dzienną, więc stół ustawisz wokół niego. Ogródek 24 m² od dziedzińca, strop 3,9 m.',
  },
  {
    floor: 0,
    column: 10,
    rooms: 4,
    area: 90.6,
    price: 1391000,
    status: 'available',
    outdoor: { kind: 'garden', area: 35 },
    note: 'Salon z aneksem na wschód, trzy sypialnie od dziedzińca i dwie łazienki. Z ogródkiem 35 m² na dziedzińcu. Strop na wysokości 3,9 m, jak w dawnej hali.',
  },
  {
    floor: 1,
    column: 1,
    rooms: 4,
    area: 102.1,
    price: 1627000,
    status: 'sold',
    note: 'Cztery pokoje i dwie łazienki: salon na wschód, sypialnie na zachód. Narożne: dodatkowe okno na południe, salon ma słońce od rana.',
  },
  {
    floor: 1,
    column: 2,
    rooms: 3,
    area: 61.8,
    price: 976000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 4.5 },
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Balkon 4,5 m² od strony dziedzińca, strop 3,5 m.',
  },
  {
    floor: 1,
    column: 3,
    rooms: 2,
    area: 44.9,
    price: 704000,
    status: 'available',
    note: 'Dwa pokoje z żeliwnym słupem w salonie. Okna sięgają wysoko, a strop ma 3,5 m, więc nawet małe mieszkanie jest jasne.',
  },
  {
    floor: 1,
    column: 4,
    rooms: 3,
    area: 62.9,
    price: 991000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 5.5 },
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Z balkonem 5,5 m² od zachodu. Jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 1,
    column: 5,
    rooms: 2,
    area: 40.3,
    price: 639000,
    status: 'sold',
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Nad bramą wjazdową, z widokiem na całą ulicę.',
  },
  {
    floor: 1,
    column: 6,
    rooms: 2,
    area: 41,
    price: 650000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 3.5 },
    note: 'Mieszkanie nad bramą przejazdową: ulicę widać stąd przez całą szerokość salonu. Balkon 3,5 m² od strony dziedzińca.',
  },
  {
    floor: 1,
    column: 7,
    rooms: 3,
    area: 63.1,
    price: 1002000,
    status: 'available',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Strop na wysokości 3,5 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 1,
    column: 8,
    rooms: 2,
    area: 44,
    price: 707000,
    status: 'reserved',
    outdoor: { kind: 'balcony', area: 3.5 },
    note: 'Mały salon z żeliwnym słupem i balkonem 3,5 m² od zachodu. Jedna ściana jest z odsłoniętej cegły, druga z nowego tynku.',
  },
  {
    floor: 1,
    column: 9,
    rooms: 3,
    area: 60.3,
    price: 942000,
    status: 'sold',
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Wysokie okna w salonie i 3,5 m do sufitu.',
  },
  {
    floor: 1,
    column: 10,
    rooms: 4,
    area: 84.7,
    price: 1276000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 7.3 },
    note: 'Salon z aneksem od ulicy, trzy sypialnie i dwie łazienki. Narożne, z oknem w ścianie szczytowej, z widokiem na komin.',
  },
  {
    floor: 2,
    column: 1,
    rooms: 3,
    area: 67.4,
    price: 1078000,
    status: 'reserved',
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Narożne, z oknem w ścianie szczytowej od południa.',
  },
  {
    floor: 2,
    column: 2,
    rooms: 3,
    area: 64.9,
    price: 1046000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 5 },
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Balkon 5 m² od dziedzińca, popołudniowe słońce w sypialni.',
  },
  {
    floor: 2,
    column: 3,
    rooms: 2,
    area: 43.2,
    price: 721000,
    status: 'available',
    note: 'Dwa pokoje: salon z aneksem od ulicy, sypialnia od dziedzińca. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 2,
    column: 4,
    rooms: 2,
    area: 38.5,
    price: 636000,
    status: 'reserved',
    outdoor: { kind: 'balcony', area: 4.8 },
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Balkon 4,8 m² od strony dziedzińca, strop 3,4 m.',
  },
  {
    floor: 2,
    column: 5,
    rooms: 3,
    area: 57,
    price: 901000,
    status: 'sold',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Okno salonu tuż nad dawną bramą przędzalni.',
  },
  {
    floor: 2,
    column: 6,
    rooms: 3,
    area: 58.2,
    price: 906000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 5.9 },
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Okno salonu tuż nad dawną bramą przędzalni.',
  },
  {
    floor: 2,
    column: 7,
    rooms: 2,
    area: 39.1,
    price: 623000,
    status: 'available',
    note: 'Salon z aneksem na wschód, cicha sypialnia na zachód. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 2,
    column: 8,
    rooms: 2,
    area: 45.6,
    price: 742000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 3.2 },
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Z balkonem 3,2 m² od zachodu. Jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 2,
    column: 9,
    rooms: 3,
    area: 64,
    price: 1036000,
    status: 'sold',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 2,
    column: 10,
    rooms: 3,
    area: 68.4,
    price: 1072000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 4.8 },
    note: 'Narożne od północy. Z okna w ścianie szczytowej widać ceglany komin, a balkon 4,8 m² wychodzi na dziedziniec.',
  },
  {
    floor: 3,
    column: 1,
    rooms: 4,
    area: 87.3,
    price: 1412000,
    status: 'available',
    note: 'Narożne od południa, więc salon dostaje poranne słońce z dwóch stron. Cztery pokoje i dwie łazienki na jednym poziomie.',
  },
  {
    floor: 3,
    column: 2,
    rooms: 3,
    area: 60.9,
    price: 963000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 5.5 },
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Balkon 5,5 m² od strony dziedzińca, strop 3,4 m.',
  },
  {
    floor: 3,
    column: 3,
    rooms: 3,
    area: 56.9,
    price: 921000,
    status: 'available',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 3,
    column: 4,
    rooms: 2,
    area: 42.4,
    price: 707000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 4.2 },
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Balkon 4,2 m² od dziedzińca, popołudniowe słońce w sypialni.',
  },
  {
    floor: 3,
    column: 5,
    rooms: 3,
    area: 62.4,
    price: 1015000,
    status: 'reserved',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Okno salonu tuż nad dawną bramą przędzalni.',
  },
  {
    floor: 3,
    column: 6,
    rooms: 3,
    area: 53.5,
    price: 890000,
    status: 'available',
    outdoor: { kind: 'balcony', area: 5.5 },
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Okno salonu tuż nad dawną bramą przędzalni.',
  },
  {
    floor: 3,
    column: 7,
    rooms: 2,
    area: 37.9,
    price: 629000,
    status: 'available',
    note: 'Salon z aneksem na wschód, cicha sypialnia na zachód. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 3,
    column: 8,
    rooms: 3,
    area: 56.4,
    price: 934000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 5.9 },
    note: 'Salon z aneksem od ulicy i dwie sypialnie od dziedzińca. Z balkonem 5,9 m² od zachodu. Jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 3,
    column: 9,
    rooms: 3,
    area: 54.1,
    price: 863000,
    status: 'available',
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Strop na wysokości 3,4 m, jedna ściana salonu z odsłoniętą cegłą.',
  },
  {
    floor: 3,
    column: 10,
    rooms: 4,
    area: 93.8,
    price: 1526000,
    status: 'sold',
    outdoor: { kind: 'balcony', area: 6.8 },
    note: 'Salon z aneksem od ulicy, trzy sypialnie i dwie łazienki. Narożne: dodatkowe okno na północ, w stronę komina.',
  },
  {
    floor: 4,
    column: 1,
    rooms: 4,
    area: 99.5,
    price: 1761000,
    status: 'reserved',
    outdoor: { kind: 'terrace', area: 19 },
    note: 'Narożne od południa, na najwyższym piętrze. Trzy sypialnie od dziedzińca i taras 19 m² od strony ulicy, wcięty w bryłę pod szedem.',
  },
  {
    floor: 4,
    column: 2,
    rooms: 4,
    area: 81.4,
    price: 1420000,
    status: 'available',
    outdoor: { kind: 'terrace', area: 15 },
    note: 'Salon z aneksem na wschód i trzy sypialnie od dziedzińca. Taras 15 m² od strony ulicy, wcięty w bryłę pod szedem.',
  },
  {
    floor: 4,
    column: 3,
    rooms: 3,
    area: 65.5,
    price: 1142000,
    status: 'available',
    note: 'Pod szedem strop unosi się ku północy. Pod wysokim szkleniem zmieści się biurko albo regał do sufitu.',
  },
  {
    floor: 4,
    column: 4,
    rooms: 3,
    area: 66.9,
    price: 1183000,
    status: 'available',
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Skośny strop szedu, świetlik od północy, najwyższe piętro budynku.',
  },
  {
    floor: 4,
    column: 5,
    rooms: 2,
    area: 46.3,
    price: 830000,
    status: 'sold',
    note: 'Salon z aneksem od ulicy i sypialnia od dziedzińca. Pod szedem: strop unosi się do 5,2 m, a świetlik od północy daje równe światło.',
  },
  {
    floor: 4,
    column: 6,
    rooms: 2,
    area: 46.8,
    price: 814000,
    status: 'available',
    note: 'Najwyższe piętro nad bramą. Szed zaczyna się tuż nad oknem salonu, więc strop sięga 5,2 m, a światło z północy jest równe do wieczora.',
  },
  {
    floor: 4,
    column: 7,
    rooms: 3,
    area: 66.2,
    price: 1167000,
    status: 'available',
    note: 'Salon z aneksem od ulicy, dwie sypialnie od cichej strony. Pod szedem: strop unosi się do 5,2 m, a świetlik od północy daje równe światło.',
  },
  {
    floor: 4,
    column: 8,
    rooms: 3,
    area: 65.1,
    price: 1153000,
    status: 'sold',
    note: 'Trzy pokoje: salon z aneksem na wschód, sypialnie na zachód. Dach szedowy nad salonem, światło z północy przez cały dzień.',
  },
  {
    floor: 4,
    column: 9,
    rooms: 4,
    area: 78.2,
    price: 1336000,
    status: 'available',
    outdoor: { kind: 'terrace', area: 14 },
    note: 'Cztery pokoje pod zębem dachu szedowego. Taras 14 m² od strony ulicy jest wcięty w bryłę, pod osłoną szedu.',
  },
  {
    floor: 4,
    column: 10,
    rooms: 4,
    area: 104.7,
    price: 1851000,
    status: 'available',
    outdoor: { kind: 'terrace', area: 18 },
    note: 'Największe mieszkanie w budynku, przy samym kominie. Dach szedowy nad salonem i taras 18 m² od strony ulicy, wcięty w bryłę.',
  },
];
