import type { Lang } from '../data/lang';

const pl = {
  skip: 'Przejdź do treści',
  ogAlt: 'Hasło Kuchnia polska, podana od nowa i biała karta dań leżąca na musztardowym stole.',
  homeLabel: 'Kminek, strona główna',
  mainNav: 'Główna nawigacja',
  language: 'Język strony',
  languageNames: { pl: 'Polski', en: 'English' },
  menuButton: 'Menu',
  nav: {
    home: 'Start',
    menu: 'Karta',
    events: 'Wydarzenia',
    about: 'O nas',
    booking: 'Rezerwacja',
  },
  reserve: 'Zarezerwuj stolik',
  slip: {
    label: 'Godziny i adres',
    title: 'Godziny',
    statusFallback: 'Otwarte od wtorku do niedzieli.',
    kitchen: 'Kuchnia do 21:00',
    address: 'Adres',
    phone: 'Telefon',
    openDays: 'Wt-Nd',
    closedDay: 'Pn',
    closed: 'zamknięte',
  },
  footer: {
    visit: 'Zajrzyj',
    hours: 'Godziny otwarcia',
    pages: 'Na tej stronie',
    contact: 'Kontakt',
    kitchenNote: 'Kuchnia zamyka się o 21:00.',
    mondayNote: 'W poniedziałek jedziemy na targ.',
    days: {
      1: 'Poniedziałek',
      2: 'Wtorek',
      3: 'Środa',
      4: 'Czwartek',
      5: 'Piątek',
      6: 'Sobota',
      0: 'Niedziela',
    },
    closed: 'zamknięte',
    kitchenUntil: 'kuchnia do',
  },
};

const en: typeof pl = {
  skip: 'Skip to content',
  ogAlt: 'The line Polish cooking, served anew, and a white menu card lying on a mustard table.',
  homeLabel: 'Kminek, home',
  mainNav: 'Main navigation',
  language: 'Site language',
  languageNames: { pl: 'Polski', en: 'English' },
  menuButton: 'Menu',
  nav: {
    home: 'Home',
    menu: 'Menu',
    events: 'Events',
    about: 'About us',
    booking: 'Booking',
  },
  reserve: 'Book a table',
  slip: {
    label: 'Opening hours and address',
    title: 'Opening hours',
    statusFallback: 'Open Tuesday to Sunday.',
    kitchen: 'Kitchen until 21:00',
    address: 'Address',
    phone: 'Phone',
    openDays: 'Tue-Sun',
    closedDay: 'Mon',
    closed: 'closed',
  },
  footer: {
    visit: 'Visit',
    hours: 'Opening hours',
    pages: 'On this site',
    contact: 'Contact',
    kitchenNote: 'The kitchen closes at 21:00.',
    mondayNote: 'On Monday we go to the market.',
    days: {
      1: 'Monday',
      2: 'Tuesday',
      3: 'Wednesday',
      4: 'Thursday',
      5: 'Friday',
      6: 'Saturday',
      0: 'Sunday',
    },
    closed: 'closed',
    kitchenUntil: 'kitchen until',
  },
};

export const shellCopy: Record<Lang, typeof pl> = { pl, en };
