import { C } from '../tokens';

export const ink: Record<string, number> = {
  k: C.ink,
  p: C.plum,
  d: C.dusk,
  r: C.berryDeep,
  b: C.berry,
  l: C.berryLight,
  g: C.gold,
  c: C.cream,
  f: C.forest,
  e: C.leaf,
  s: C.sprout,
  B: C.blueDeep,
  m: C.skyMid,
  y: C.sky,
  t: C.stone,
  w: C.white,
};

export const berry = [
  '.......kk.......',
  '...kkk.kfk.kkk..',
  '..kseekkfkkeesk.',
  '.kkseeeffeeeskk.',
  '.kbkkeeffeekkbk.',
  'kblbbkkkkkkbbbbk',
  'kllbbbbbbbbbbbrk',
  'klbbgbbbbbbgbbrk',
  'kbbbwkbbbbwkbbrk',
  'kbgbkkbbbbkkbgrk',
  'kbbbbbkbbkbbbbrk',
  '.kbbbbbkkbbbbrk.',
  '.kbgbbbbbbbgbrk.',
  '..kbbbbbbbbbrk..',
  '..kbbbgbbbbrrk..',
  '...kbbbbbbrrk...',
  '....kbbbbrrk....',
  '.....kkkkkk.....',
] as const;

export const berryBlink = berry.map((row, i) => (i === 8 ? 'kbbbbbbbbbbbbbrk' : i === 9 ? 'kbgkkkbbbbkkkgrk' : row));

export const berrySquash = [
  '................',
  '.......kk.......',
  '...kkk.kfk.kkk..',
  '..kseekkfkkeesk.',
  '.kkseeeffeeeskk.',
  'kkbkkeeffeekkbkk',
  'kblbbkkkkkkbbbbk',
  'kllbbbbbbbbbbbrk',
  'klbbwkbbbbwkbbrk',
  'kbgbkkbbbbkkbgrk',
  'kbbbbbkbbkbbbbrk',
  'kbbbbbbkkbbbbbrk',
  '.kbgbbbbbbbgbrk.',
  '.kbbbbbbbbbbbrk.',
  '..kbbbgbbbbrrk..',
  '...kbbbbbbrrk...',
  '....kbbbbrrk....',
  '.....kkkkkk.....',
] as const;

export const berryCheer = berry.map((row, i) =>
  i === 8 ? 'kbbbkkbbbbkkbbrk' : i === 9 ? 'kbgkbbkbbkbbkgrk' : i === 10 ? 'kbbbbkkkkkkbbbrk' : i === 11 ? '.kbbbbkllkbbbrk.' : row,
);

export const mini = [
  '...kfk..',
  '.kseesk.',
  'kbkeekbk',
  'kllbbbrk',
  'kbgbbgrk',
  '.kbbbrk.',
  '..kbrk..',
  '...kk...',
] as const;

export const coin = [
  [
    '..kkkk..',
    '.kggggk.',
    'kgccgggk',
    'kgcggggk',
    'kggggggk',
    'kggggrdk',
    '.kgdddk.',
    '..kkkk..',
  ],
  [
    '...kk...',
    '..kcgk..',
    '..kcgk..',
    '..kggk..',
    '..kggk..',
    '..kgdk..',
    '..kgdk..',
    '...kk...',
  ],
  [
    '..kkkk..',
    '.kggggk.',
    'kggggcck',
    'kgggggck',
    'kggggggk',
    'kdrggggk',
    '.kdddgk.',
    '..kkkk..',
  ],
] as const;

export const sparkle = ['..w..', '..w..', 'ww.ww', '..w..', '..w..'] as const;
export const sparkleSmall = ['.w.', 'w.w', '.w.'] as const;

export const habitIcons: Record<string, readonly string[]> = {
  water: [
    '..kkkkkkkk..',
    '..kwwwwwwk..',
    '..kmyyyyyk..',
    '..kmyyyyyk..',
    '..kmmyyyyk..',
    '..kBmmyyyk..',
    '..kBmmmyyk..',
    '..kBBmmmmk..',
    '..kBBmmmmk..',
    '..kBBBmmmk..',
    '..kwwwwwwk..',
    '...kkkkkk...',
  ],
  walk: [
    '............',
    '.....kkkk...',
    '....kbbbbk..',
    '....kblbbk..',
    '....kbbbbk..',
    '...kbbbbbk..',
    '..kbbbbbbk..',
    '.kbbbbbbbbk.',
    'kbbcbcbcbbbk',
    'kccccccccccc',
    'kttttttttttk',
    '.kkkkkkkkkk.',
  ],
  book: [
    '............',
    'kkkkk..kkkkk',
    'kcccckkcccck',
    'kckkcckcckck',
    'kcccckkcccck',
    'kckkcckcckck',
    'kcccckkcccck',
    'kckkcckcckck',
    'kcccckkcccck',
    'kbbbbkkbbbbk',
    '.kkkkbbkkkk.',
    '.....kk.....',
  ],
  phone: [
    '...kkkkkk...',
    '..kppppppk..',
    '..kpBBBBpk..',
    '..kpBgBBpk..',
    '..kpBBgBpk..',
    '..kpBBBBpk..',
    '..kpBBgBpk..',
    '..kpBBBBpk..',
    '..kppppppk..',
    '..kppkkppk..',
    '...kkkkkk...',
    '............',
  ],
  stretch: [
    '.....kk.....',
    '....kcck....',
    '....kcck....',
    '.....kk.....',
    'kk..kbbk..kk',
    'kckkbbbbkkck',
    '.kccbbbbcck.',
    '....kbbk....',
    '....kbbk....',
    '...kbkkbk...',
    '..kbk..kbk..',
    '..kk....kk..',
  ],
  dumbbell: [
    '............',
    '............',
    'kk........kk',
    'kpk......kpk',
    'kpkkkkkkkkpk',
    'kpttttttttpk',
    'kpkkkkkkkkpk',
    'kpk......kpk',
    'kk........kk',
    '............',
    '............',
    '............',
  ],
  sleep: [
    '............',
    '.......kkkk.',
    '.........k..',
    '........k...',
    '.......kkkk.',
    '............',
    'k...........',
    'kkkkkkkkkkkk',
    'kcccckwwwwwk',
    'kcccckkkkkkk',
    'kkkkkkkkkkkk',
    'k..........k',
  ],
  carrot: [
    '.......k.k..',
    '......kekek.',
    '.......kek..',
    '......kkkk..',
    '.....kggrk..',
    '.....kgrrk..',
    '....kggrk...',
    '....kgrrk...',
    '...kggrk....',
    '...kgrk.....',
    '..kgrk......',
    '..kk........',
  ],
};

export const check = [
  '.kkkkkkkk.',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  'kccccccccd',
  '.dddddddd.',
] as const;

export const checkOn = [
  '.kkkkkkkk.',
  'keeeeeeesk',
  'keeeeeesk.',
  'keeeeesk..',
  'kseeesk...',
  'kssesk....',
  'kssskeeeek',
  'keskeeeeek',
  'keeeeeeeek',
  '.kkkkkkkk.',
] as const;

export const tick = [
  '........ss',
  '.......ss.',
  '......ss..',
  'ss...ss...',
  '.ss.ss....',
  '..sss.....',
  '...s......',
] as const;

export const tabIcons: Record<string, readonly string[]> = {
  quests: [
    '.kkkkkkkk.',
    'kccccccck.',
    'kckkcckck.',
    'kccccccck.',
    'kckkckkck.',
    'kccccccck.',
    'kckkkcckk.',
    'kccccccck.',
    '.kkkkkkk..',
    '..........',
  ],
  streak: [
    '....kk....',
    '...kgk....',
    '..kggk.k..',
    '..kgggkgk.',
    '.kggcggggk',
    '.kgcccgggk',
    'kggcwcggk.',
    'kggcccggk.',
    '.kggggggk.',
    '..kkkkkk..',
  ],
  garden: [
    '...kk.kk..',
    '..kssksek.',
    '..ksseeek.',
    '...kkekk..',
    '.....k....',
    '.kkkkkkkk.',
    '.kddddddk.',
    '..kddddk..',
    '..kddddk..',
    '...kkkk...',
  ],
  week: [
    '..........',
    '.......kk.',
    '.......kk.',
    '....kk.kk.',
    '....kk.kk.',
    '.kk.kk.kk.',
    '.kk.kk.kk.',
    '.kk.kk.kk.',
    'kkkkkkkkkk',
    '..........',
  ],
};

export const cloud = [
  '.......wwww.........',
  '.....wwwwwwww.......',
  '..wwwwwwwwwwwww.....',
  '.wwwwwwwwwwwwwwwww..',
  'wwwwwwwwwwwwwwwwwwww',
  'wywywwwwwwwwwwwywywy',
  '.y.y.yyyyyyyyy.y.y..',
] as const;

export const cloudSmall = ['...wwww...', '.wwwwwwww.', 'wwwwwwwwww', 'ywywywywyw', '.y.yyyy.y.'] as const;

export const sun = [
  '.....g.....',
  '..g..g..g..',
  '...ggggg...',
  '..ggcccgg..',
  'gggcccccggg',
  '..ggcccgg..',
  '...ggggg...',
  '..g..g..g..',
  '.....g.....',
] as const;

export const can = [
  '....kkkkk.........',
  '...k.....k......kk',
  '...k.....k.....kgk',
  '.kkkkkkkkkkk..kgk.',
  'kgcgggggggrk.kgk..',
  'kgcggggggggrkgk...',
  'kgcggggggggrgk....',
  'kggggggggggrk.....',
  'kggggggggggrk.....',
  'kgggggggggrrk.....',
  'krrrrrrrrrrrk.....',
  '.kkkkkkkkkkk......',
] as const;

export const chestShut = [
  '.kkkkkkkkkkkkkk.',
  'krrrrrrrrrrrrrrk',
  'krbbbbbbbbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'kkkkkkkggkkkkkkk',
  'krrrrrkgdkrrrrrk',
  'krbbbbkgdkbbbbrk',
  'krbbbbbkkbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'krrrrrrrrrrrrrrk',
  'kkkkkkkkkkkkkkkk',
] as const;

export const chestOpenLid = ['.kkkkkkkkkkkkkk.', 'kppppppppppppppk', 'kkkkkkkkkkkkkkkk'] as const;

export const chestLid = [
  '.kkkkkkkkkkkkkk.',
  'krrrrrrrrrrrrrrk',
  'krbbbbbbbbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'kkkkkkkkkkkkkkkk',
] as const;

export const chestBase = [
  'kkkkkkkkkkkkkkkk',
  'kppppppppppppppk',
  'krrrrrkgdkrrrrrk',
  'krbbbbkgdkbbbbrk',
  'krbbbbbkkbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'krbbbbbbbbbbbbrk',
  'krrrrrrrrrrrrrrk',
  'kkkkkkkkkkkkkkkk',
] as const;

export const lock = ['..kkk..', '.k...k.', '.k...k.', 'kkkkkkk', 'ktttttk', 'kttkttk', 'ktttttk', 'kkkkkkk'] as const;

export const rake = [
  '...........kk',
  '..........kdk',
  '.........kdk.',
  '........kdk..',
  '.......kdk...',
  '......kdk....',
  '.kkkkkdk.....',
  'ktttttk......',
  'kt.t.tk......',
  'k.k.k.k......',
] as const;

export const fence = [
  '.k...k...k.',
  'kck.kck.kck',
  'kckkkckkkck',
  'kcccccccccc',
  'kckkkckkkck',
  'kck.kck.kck',
  'kckkkckkkck',
  'kcccccccccc',
  'kckkkckkkck',
  'kck.kck.kck',
  'kkk.kkk.kkk',
] as const;

export const seed = ['.kkk.', 'kdddk', 'kdtdk', 'kdddk', '.kkk.'] as const;

export const plantStages: Record<string, readonly string[]> = {
  nasionko: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kkk.......',
    '.....kdddk......',
    '.....kdtdk......',
    '......kkk.......',
    '................',
  ],
  listek: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.........kk.....',
    '........kssk....',
    '.......kssek....',
    '.......kseek....',
    '........kek.....',
    '........ke......',
    '........kk......',
    '........k.......',
    '................',
  ],
  sadzonka: [
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kssk......',
    '...kk.ksek.kk...',
    '..ksskkekkssk...',
    '..ksseekeesek...',
    '...kseekeeek....',
    '....kkekekk.....',
    '......kek.......',
    '.......ek.......',
    '.......kk.......',
    '.......k........',
    '................',
    '................',
  ],
  kwiat: [
    '......kkkk......',
    '.....kwwwwk.....',
    '....kwwggwwk....',
    '....kwggggwk....',
    '....kwwggwwk....',
    '.....kwwwwk.....',
    '..kk..kekk..kk..',
    '.ksskk.ke..kssk.',
    '.ksseekkekkeesk.',
    '..kseeekeeeesk..',
    '...kkeeeeeekk...',
    '.....kkeekk.....',
    '.......ek.......',
    '.......kk.......',
    '................',
    '................',
  ],
  owoc: [
    '...kk......kk...',
    '..ksskk..kkssk..',
    '..ksseekkeessk..',
    '...kseeekeeesk..',
    '....kkeekeekk...',
    '......kkekk.....',
    '...kk..kek..kk..',
    '..kfffk.k..kfffk',
    '.kblbbbk..kblbbk',
    '.kbbgbrk..kbbgrk',
    '.kbgbbrk..kbgbrk',
    '..kbbrk....kbrk.',
    '...kbk......kk..',
    '....k...........',
    '................',
    '................',
  ],
};

export const growPoses = [
  plantStages.kwiat,
  [
    '................',
    '................',
    '.......kkk......',
    '......kssskk....',
    '.....kk.kek.....',
    '..kk...kek..kk..',
    '.ksskk.ke..kssk.',
    '.ksseekkekkeesk.',
    '..kseeekeeeesk..',
    '...kkeeekeeek...',
    '....kfk.ke......',
    '...kssk.ke......',
    '...kssk.kk......',
    '....kk..........',
    '................',
    '................',
  ],
  plantStages.owoc,
] as const;

export const statusBattery = ['kkkkkkkkkk.', 'kggggggg.kk', 'kggggggg.kk', 'kggggggg.kk', 'kkkkkkkkkk.'] as const;
export const statusWifi = ['.kkkkk.', 'k.....k', '..kkk..', '.k...k.', '...k...'] as const;
